# Generated by Django 4.1.7 on 2023-02-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_membre', models.CharField(max_length=45)),
                ('prenom_membre', models.CharField(max_length=45)),
                ('datenaissance', models.DateField()),
                ('sexe', models.CharField(choices=[('Masculin', 'masculin'), ('Feminin', 'feminin')], max_length=45)),
                ('telephone', models.CharField(max_length=45)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('adresse', models.CharField(max_length=45)),
                ('nationalite', models.CharField(max_length=45)),
                ('etat', models.CharField(choices=[('Actif', 'actif'), ('Non actif', 'non actif')], max_length=45)),
            ],
        ),
    ]
