# Generated by Django 4.1.7 on 2023-02-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comembre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cotisation', models.DateField()),
                ('montant_paye', models.IntegerField()),
                ('motif', models.CharField(choices=[('Sociale', 'sociale'), ('Epargne', 'epargne')], max_length=62)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cooperative')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.membre')),
            ],
        ),
    ]
