# Generated by Django 4.1.7 on 2023-02-21 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_remboursement', models.DateField()),
                ('montant_remboursement', models.IntegerField()),
                ('reste_credit', models.IntegerField()),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.credit')),
            ],
        ),
    ]
