# Generated by Django 4.1.7 on 2023-02-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remboursement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperative',
            name='membre',
        ),
    ]
